#!/bin/bash
set -e

# build .deb package base on rateup binary file which generated by make
# the package made by this script also depends cuda-repo-ubuntu1804-11-1-local_11.1.0-455.23.05-1_amd64.deb
# make sure cuda has installed before installing this.

if [ ! -e build/rateup ]; then
    echo "can't find rateup binary file"
    exit 1
fi

mkdir -p rateup_deb/DEBIAN/ && cd rateup_deb/
echo -e "Package: rateup-db
Version: 1.0.1-1ubuntu18.04
Architecture: amd64
Maintainer: Rateup Team <dongyang.li@rateup.com.cn>
Section: database
Priority: optional
Depends: libboost-filesystem1.65.1,libunwind8
Required: cuda-repo-ubuntu1804-11-1-local_11.1.0-455.23.05-1_amd64.deb
Installed-Size: 66666
Description: Rateup is a full featured GPU accelerated Database.
" > DEBIAN/control

mkdir -p usr/sbin/
cp ../build/rateup usr/sbin/
cp ../src/server/mysql/share/english/errmsg.sys usr/sbin/
mkdir -p usr/sbin/lib/
cp ../build/libariesdatatype.a usr/sbin/lib/
mkdir -p usr/sbin/include/
cp ../src/AriesDataType.h usr/sbin/include/
cp ../src/AriesColumnType.h usr/sbin/include/
cp ../src/AriesDefinition.h usr/sbin/include/
cp ../src/AriesColumnDataIterator.hxx usr/sbin/include/
cp ../src/CudaAcc/algorithm/cpptraits.hxx usr/sbin/include/
cp ../src/CudaAcc/algorithm/aries_char.hxx usr/sbin/include/
cp ../src/datatypes/aries_types.hxx usr/sbin/include/
cp ../src/datatypes/functions.hxx usr/sbin/include/
cp ../src/datatypes/decimal.hxx usr/sbin/include/
cp ../src/datatypes/AriesIntervalTime.hxx usr/sbin/include/
cp ../src/datatypes/AriesDatetime.hxx usr/sbin/include/
cp ../src/datatypes/AriesDate.hxx usr/sbin/include/
cp ../src/datatypes/AriesTimeCalc.hxx usr/sbin/include/
cp ../src/datatypes/AriesTimestamp.hxx usr/sbin/include/
cp ../src/datatypes/AriesYear.hxx usr/sbin/include/
cp ../src/datatypes/AriesInnerHelper.hxx usr/sbin/include/
cp ../src/datatypes/AriesTime.hxx usr/sbin/include/
cp ../src/datatypes/AriesSqlFunctions.hxx usr/sbin/include/
cp ../src/datatypes/AriesCastFunctions.hxx usr/sbin/include/
cp ../src/datatypes/AriesDateFormat.hxx usr/sbin/include/
cp ../src/datatypes/AriesDataTypeUtil.hxx usr/sbin/include/
cp ../src/datatypes/AriesTruncateFunctions.hxx usr/sbin/include/

cd ..
# <name>_<VersionNumber>-<CUDAVersion>-<ComputeCapability>-<DebianRevisionNumber>_<DebianArchitecture>.deb
dpkg -b rateup_deb rateup_1.0.0-cuda11.1-compute6.1-1ubuntu18.04_amd64.deb

rm -rf rateup_deb

echo "Done."
